language: go

go:
- '1.8'

install:
- go get github.com/Sirupsen/logrus
- go get gopkg.in/yaml.v2
- go get github.com/spf13/cobra
- go get golang.org/x/crypto/ssh
- go get github.com/mitchellh/gox
- go get github.com/inconshreveable/mousetrap
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/pkg/sftp

script:
 - go generate
 - gox -osarch="darwin/amd64 linux/386 linux/amd64 windows/386 windows/amd64"
 - mv openshifter_darwin_amd64 openshifter && tar czf openshifter-macos-amd64.tar.gz openshifter && rm openshifter
 - mv openshifter_linux_amd64 openshifter && tar czf openshifter-linux-amd64.tar.gz openshifter && rm openshifter
 - mv openshifter_linux_386 openshifter && tar czf openshifter-linux-386.tar.gz openshifter && rm openshifter
 - mv openshifter_windows_amd64.exe openshifter.exe && tar czf openshifter-windows-amd64.tar.gz openshifter.exe && rm openshifter.exe
 - mv openshifter_windows_386.exe openshifter.exe && tar czf openshifter-windows-386.tar.gz openshifter.exe && rm openshifter.exe

deploy:
  provider: releases
  api_key:
    secure: IBXS8fg30PhjOPqsdUORMXeMhaiAEbeIuJIt8ZHZwcTy+8hIA8dxiIw8O/jAzcWIdSGtT7Q1ebUwbHNK8u82HN1o1mUfwxla752Pm58KHEhOvSzlolYoaWS1eDefcMoZbUqOxuUCyWxBGu9G2vGTwNA6rafTqtGHU2rinYUXzEw8NF/QI/ftBf0vRTU/CT34ZXqEtxt4pvTdVqnPxfIv+0dzvoC59jxX5d2BZtfFcft7GOFf/DU+H7+4t+WGmpL97+hJ97OubK/SYvlBqztt01KtyVP+OzYwV95EC+Toint7ZVc84Oet9DPwg+dbhrPBilST3lXSjuJtrspqOzKlzCbsASzpJb2Hf3KdZb4ghNK2JvMe/GDOOOcqg8dFJF9jmwUgPyAIRIzUt3VUa734drwxWcPPzE8kc1qMsOqKGRm7Pzf6l4Br/a4WN/VxTqKpjW2lA41DEM96TtAD73OS0k80c+ej++ltaWc/DiJHfUMbu3VSEcasBVdbmreCNwA7fPurEoOSopZ7TDJOJ7EqXEB24pHRpd0VSYFcjAGeuLymt0SCQm7pwdx+cOFn0lNSDc5jFzb8DxOQ+ln1Tx4O9EZtP2yAZ18+wQXVfQqfmflxeyiZ+J+4wGasiTY4PhKl4B/VF5rJvzWiCQIm4Y9RQskH+ACq7qoUE1WEiTsh/f0=
  file:
    - openshifter-macos-amd64.tar.gz
    - openshifter-linux-amd64.tar.gz
    - openshifter-linux-386.tar.gz
    - openshifter-windows-amd64.tar.gz
    - openshifter-windows-386.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: osevg/openshifter
